### ISSUE TITLE
Ability to change the order of script tags or load common chunks first by default

### ISSUE THREAD

**Issue by nelix** [ampedandwired/html-webpack-plugin#4]
I'm using the common chunks plugin with this, and I need to load my vendor.js file before my app.js (otherwise webpackJson function is undefined in app.js)
http://webpack.github.io/docs/code-splitting.html
loading the common chunk first is documented here
I know I can use the template, but I think this would be useful.

**Comment by ampedandwired** [comment]
Apologies for the delay in getting back to you, I've had a lot going on the last couple of months. I agree an ordering mechanism would be great. I'll see what I can do.

**Comment by bebraw** [comment]
I ran into this issue with `CommonsChunkPlugin`. Great work otherwise.

Does webpack have some sort of dependency information that you can access during the process? Ideally it should just figure out the correct order internally I think.

**Comment by ampedandwired** [comment]
Yes, the webpack stats contain chunk dependency info, so I'm planning on doing exactly that. Will have a stab at it this weekend.

**Comment by pikeas** [comment]
Any luck with this?

**Comment by izaakschroeder** [comment]
@nelix @pikeas see above PR.

**Comment by ampedandwired** [comment]
Should be fixed in 1.2 - let me know if you see any problems.

**Comment by filipmares** [comment]
Not sure i understand how we can control the order of the scripts. I'm still seeing out of order scripts. Running 1.6.1.

Is it the entry order that dictates order of scripts appended to HTML?

**Comment by jantimon** [comment]
Yes:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L203
